### ISSUE TITLE
Not work at all !

### ISSUE THREAD

**Issue by Nokia808** [flathub/io.github.JakubMelka.Pdf4qt#1]
Hello ! 

I installed this program on my Fedora 38. It does not work because I can not open by it any PDF file at all ! Just click on "Open" the program will crashed !

If I right click a PDF then left click on any of PDF4QT then program will open without opening the right clicked PDF - it will opened as native !

I think it is a problem with permissions ....

**Comment by JakubMelka** [comment]
Hello, I tested it on Ubuntu (works) and on Mint (does not work). I think this is not permissions. Please start the program via console. Does it display message about missing **"xapp-gtk3-module"** ? If yes, please try to install this package (xapp). Does it solve the problem?

**Comment by Nokia808** [comment]
Hello again. 

Yes, as you corrected ! I run program via command line & I received such error message. But, there is very bad news: "xapp-gtk3-module" package is not available in official Fedora repositories nor in RPMFusion repositories !!

**Comment by JakubMelka** [comment]
I will try to solve it somehow.

**Comment by JakubMelka** [comment]
OK, I figured out, that if I do not use native open/save file windows, but use only Qt provided windows, application seems to be working. I will fix it and then upgrade flathub.

**Comment by JakubMelka** [comment]
Unfortunately, it does not work with flatpak. It crashes in the system library (gtk) and I do not know why.

**Comment by JakubMelka** [comment]
Hello @Nokia808, I have posted an update, it should work now. Please reopen the issue, if error occurs again.
