### ISSUE TITLE
Updating to 1.3.6

### ISSUE THREAD

**Issue by sith-on-mars** [flathub/io.github.JakubMelka.Pdf4qt#3]
Would it be fine to update the Flatpak version to 1.3.6? Thanks heaps!

**Comment by JakubMelka** [comment]
Hello, yes, I am planning to do it - but during the holidays, I will try to fix more bugs and then release 1.3.7.

**Comment by JakubMelka** [comment]
Hello @sith-on-mars , it is updated now on 1.3.7. Please install it.
